# Generated by Django 5.2.17 on 2026-09-02 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_channel', models.CharField(max_length=50)),
                ('campaign_id', models.CharField(blank=True, max_length=100)),
                ('creative', models.CharField(blank=True, max_length=100)),
                ('identity_level', models.CharField(choices=[('anonymous', 'Anonymous'), ('social_handle', 'Social handle known'), ('email_known', 'Email known')], default='anonymous', max_length=30)),
                ('social_handle', models.CharField(blank=True, max_length=100)),
                ('landing_context', models.TextField(blank=True)),
                ('landing_timestamp', models.DateTimeField(auto_now_add=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('visitor', 'Visitor'), ('conversation_started', 'Conversation started'), ('value_event', 'Value event'), ('auth_started', 'Auth started'), ('consented', 'Consented'), ('patient_created', 'Patient created'), ('escalation_sent', 'Escalation sent')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.leadsession')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_health_info', models.BooleanField(default=False)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinic')),
                ('origin_lead_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_sessions', to='core.leadsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('guest', 'Guest'), ('patient', 'Patient'), ('ai', 'Nightingale AI')], max_length=20)),
                ('content', models.TextField()),
                ('redacted_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.leadsession')),
                ('origin_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_messages', to='core.message')),
                ('patient_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.patientsession')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=500)),
                ('status', models.CharField(default='active', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provenance_pointer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_provenance', to='core.message')),
                ('patient_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_items', to='core.patientsession')),
            ],
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triage_summary', models.JSONField(default=list)),
                ('profile_snapshot', models.JSONField(default=dict)),
                ('provenance_points', models.JSONField(default=list)),
                ('acquisition_context', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('under_review', 'Under review'), ('responded', 'Responded')], default='sent', max_length=30)),
                ('clinician_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggering_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.message')),
                ('patient_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='core.patientsession')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('risk_reason', models.CharField(max_length=500)),
                ('confidence', models.CharField(max_length=10)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.message')),
            ],
        ),
    ]
